spring.application.name=foodordering

spring.datasource.url=jdbc:postgresql://localhost:5432/food_ordering_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
